############# Auth #############
login_check:
  path: /api/login_check

############# Machines #############
createMachine:
  path: /api/createMachine
  controller: App\Controller\MachineController::createMachine
  methods: POST

getUserMachine:
  path: /api/getUserMachines
  controller: App\Controller\MachineController::getUserMachines
  methods: POST